#!/bin/bash
# Phase 2 Verification Script

BASE="http://localhost:3001/api"
COOKIE_JAR_OWNER="/tmp/sa_owner_cookies.txt"
COOKIE_JAR_MEMBER="/tmp/sa_member_cookies.txt"

echo "=== Phase 2 Verification ==="
echo ""

# 1. Clean DB first
node -r dotenv/config -e "
const prisma = require('./src/prisma');
async function main() {
  await prisma.workspaceAccess.deleteMany();
  await prisma.socialAccount.deleteMany();
  await prisma.workspace.deleteMany();
  await prisma.membership.deleteMany();
  await prisma.user.deleteMany();
  await prisma.organization.deleteMany();
  console.log('Database cleaned');
  await prisma.\$disconnect();
  process.exit(0);
}
main();
" 2>/dev/null

# 2. Register Owner
echo "--- 2. Register OWNER ---"
REGISTER_RESP=$(curl -s -c "$COOKIE_JAR_OWNER" -X POST "$BASE/auth/register" \
  -H "Content-Type: application/json" \
  -d '{"email":"owner@agency.com","password":"password123","name":"Agency Owner","orgName":"Creative Agency"}')
ORG_ID=$(echo "$REGISTER_RESP" | python3 -c "import sys,json; print(json.load(sys.stdin)['organization']['id'])" 2>/dev/null)
OWNER_ID=$(echo "$REGISTER_RESP" | python3 -c "import sys,json; print(json.load(sys.stdin)['user']['id'])" 2>/dev/null)
echo "ORG_ID=$ORG_ID"
echo "OWNER_ID=$OWNER_ID"
echo ""

# 3. Create Workspace
echo "--- 3. Create Workspace ---"
WS_RESP=$(curl -s -b "$COOKIE_JAR_OWNER" -X POST "$BASE/workspaces" \
  -H "Content-Type: application/json" \
  -d "{\"organizationId\":\"$ORG_ID\",\"brandName\":\"Nike Running\",\"website\":\"https://nike.com\",\"cta\":\"Shop Air Max\",\"defaultHashtags\":[\"#nike\",\"#justdoit\"],\"brandVoice\":\"Energetic and inspiring\",\"emojiStyle\":\"many\"}")
echo "$WS_RESP" | python3 -m json.tool 2>/dev/null || echo "$WS_RESP"
WORKSPACE_ID=$(echo "$WS_RESP" | python3 -c "import sys,json; print(json.load(sys.stdin)['workspace']['id'])" 2>/dev/null)
echo "WORKSPACE_ID=$WORKSPACE_ID"
echo ""

# 4. Check if 3 SocialAccount rows were created
echo "--- 4. Verify SocialAccounts auto-creation ---"
SOC_ACCTS=$(echo "$WS_RESP" | python3 -c "import sys,json; print([sa['platform'] + ':' + sa['status'] for sa in json.load(sys.stdin)['workspace']['socialAccounts']])" 2>/dev/null)
echo "Social Accounts: $SOC_ACCTS"
if [[ "$SOC_ACCTS" == *"LINKEDIN:NOT_CONNECTED"* && "$SOC_ACCTS" == *"PINTEREST:NOT_CONNECTED"* && "$SOC_ACCTS" == *"YOUTUBE:NOT_CONNECTED"* ]]; then
  echo "✅ PASS: 3 NOT_CONNECTED SocialAccounts auto-created!"
else
  echo "❌ FAIL: Incorrect SocialAccounts list: $SOC_ACCTS"
fi
echo ""

# 5. Invite a Member
echo "--- 5. Invite member to Org ---"
INVITE_RESP=$(curl -s -b "$COOKIE_JAR_OWNER" -X POST "$BASE/organizations/$ORG_ID/members" \
  -H "Content-Type: application/json" \
  -d '{"email":"designer@agency.com","role":"MEMBER","name":"Designer User"}')
echo "$INVITE_RESP" | python3 -m json.tool 2>/dev/null || echo "$INVITE_RESP"
MEMBER_ID=$(echo "$INVITE_RESP" | python3 -c "import sys,json; print(json.load(sys.stdin)['membership']['user']['id'])" 2>/dev/null)
echo "MEMBER_ID=$MEMBER_ID"
echo ""

# 6. Log in as Member
echo "--- 6. Login as MEMBER ---"
MEMBER_LOGIN=$(curl -s -c "$COOKIE_JAR_MEMBER" -X POST "$BASE/auth/login" \
  -H "Content-Type: application/json" \
  -d '{"email":"designer@agency.com","password":"password123"}') # default password generated by invite is password123
echo "MEMBER Logged In"
echo ""

# 7. Member accesses workspace before access granted — should get 403
echo "--- 7. Member access WITHOUT workspace access (expect 403) ---"
STATUS1=$(curl -s -o /dev/null -w "%{http_code}" -b "$COOKIE_JAR_MEMBER" "$BASE/workspaces/$WORKSPACE_ID")
echo "Status: $STATUS1"
if [ "$STATUS1" = "403" ]; then
  echo "✅ PASS: Member access correctly denied"
else
  echo "❌ FAIL: Expected 403, got $STATUS1"
fi
echo ""

# 8. Grant Workspace Access to Member
echo "--- 8. Grant Workspace Access ---"
GRANT_RESP=$(curl -s -b "$COOKIE_JAR_OWNER" -X POST "$BASE/workspaces/$WORKSPACE_ID/access" \
  -H "Content-Type: application/json" \
  -d "{\"userId\":\"$MEMBER_ID\"}")
echo "$GRANT_RESP" | python3 -m json.tool 2>/dev/null || echo "$GRANT_RESP"
echo ""

# 9. Member accesses workspace after access granted — should get 200
echo "--- 9. Member access WITH workspace access (expect 200) ---"
STATUS2=$(curl -s -o /dev/null -w "%{http_code}" -b "$COOKIE_JAR_MEMBER" "$BASE/workspaces/$WORKSPACE_ID")
echo "Status: $STATUS2"
if [ "$STATUS2" = "200" ]; then
  echo "✅ PASS: Member access granted successfully!"
else
  echo "❌ FAIL: Expected 200, got $STATUS2"
fi
echo ""

# 10. Revoke Workspace Access
echo "--- 10. Revoke Workspace Access ---"
REVOKE_RESP=$(curl -s -b "$COOKIE_JAR_OWNER" -X DELETE "$BASE/workspaces/$WORKSPACE_ID/access/$MEMBER_ID")
echo "$REVOKE_RESP" | python3 -m json.tool 2>/dev/null || echo "$REVOKE_RESP"
echo ""

# 11. Member accesses workspace after access revoked — should get 403
echo "--- 11. Member access after workspace access revoked (expect 403) ---"
STATUS3=$(curl -s -o /dev/null -w "%{http_code}" -b "$COOKIE_JAR_MEMBER" "$BASE/workspaces/$WORKSPACE_ID")
echo "Status: $STATUS3"
if [ "$STATUS3" = "403" ]; then
  echo "✅ PASS: Member access revoked successfully!"
else
  echo "❌ FAIL: Expected 403, got $STATUS3"
fi
echo ""

echo "=== Phase 2 Verification Complete ==="

rm -f "$COOKIE_JAR_OWNER" "$COOKIE_JAR_MEMBER"
